### ISSUE TITLE
Is there a function equivalent to loadWifiList on iOS?

### ISSUE THREAD

**Issue by guiac** [JuanSeBestia/react-native-wifi-reborn#167]

**Comment by jenschr** [comment]
No. Just read the documentation?
https://github.com/JuanSeBestia/react-native-wifi-reborn#only-android

It clearly states that this is Android only. If you just search this rather than opening an issue (when you clearly just have a question), you would save us all a lot of time. Here is my first result from Google https://developer.apple.com/forums/thread/39204 and as you can see this was replied to 5 years ago and it's still valid today. Please close this (non)issue?
