### ISSUE TITLE
Android - Error: On Android 10, the user has to enable wifi manually

### ISSUE THREAD

**Issue by 9kmmr** [JuanSeBestia/react-native-wifi-reborn#205]
In v4.3.8 when using **connectToProtectedSSID**, I got this error  when trying to connect to a wifi :

`WifiManager.connectToProtectedSSID(currentSSID, wifiPass, false).then(
        () => {
          console.log("wifi is in range");        
        },
        (err) => {
          console.log(err);
          console.log("wifi is not in range");        
        }
 );`
 
and got the error: [Error: On Android 10, the user has to enable wifi manually.]
What does it mean ? This can not be used in Android 10 ?

**Comment by romaob** [comment]
This is a security restriction on Android, is just because the wifi is off, it can connect with the provided SSID, but it can not automatically turn the wifi on/off, this also happens with Location.
In this case, I show a message asking the user to turn on wifi and try again, you can also show a button to open wifi settings or listen until the user enables wifi, but only the user can turn it on and off.
