### ISSUE TITLE
4.10.0 doesn't build

### ISSUE THREAD

**Issue by DavideViolante** [JuanSeBestia/react-native-wifi-reborn#345]
"react-native-wifi-reborn": "4.10.0",
"react-native": "0.69.10",
```
[13:50:18] dave@DaveXPS:~/job/company/my-project-app$ npm run build:android

> my-project@1.15.6 build:android
> cd android && ./gradlew app:assembleRelease


FAILURE: Build failed with an exception.

* Where:
Script '/home/dave/job/company/my-project-app/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 250

* What went wrong:
A problem occurred evaluating script.
> Calling `[node, /home/dave/job/company/my-project-app/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
  
  The current character read is 'i' with an int value of 105
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  info Run CLI with --verbose flag for more details.
  ^. Output: info Run CLI with --verbose flag for more details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

v4.9.0 builds fine.

**Comment by evan1715** [comment]
i'm going to assume it's with the namespace.

[v4.10.0 commit](https://github.com/JuanSeBestia/react-native-wifi-reborn/commit/451b92c53a0e173cd48f95b38f0bcaba2c5b63a8) adds support for react-native 0.73 which will [require namespace declared](https://github.com/react-native-community/discussions-and-proposals/issues/671) in accordance with [AGP 8.x](https://developer.android.com/build/releases/gradle-plugin#namespace-dsl). 

support for namespace was added in AGP 7.3 which is in RN0.71. since you are on RN0.69, any package update that uses native code has the potential to now break your app.

as a side note, 0.69 targets sdkVersion/API 31. as part of [play store's newer policy](https://support.google.com/googleplay/android-developer/answer/11926878?hl=en), all apps will be required to be within 2 years of a release. so, in one year, your app will no longer be available to new users or be able to update unless you update your react-native. i recommend keeping all packages up-to-date at least once every six months to not create too big of a burden. i check them about every three months. you can try their [upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.69.10&to=0.72.6) to assist.

**Comment by DavideViolante** [comment]
We upgraded react and it works.
