### ISSUE TITLE
WifiManager.loadWifiList is not working on iOS 

### ISSUE THREAD

**Issue by Skvitthani** [JuanSeBestia/react-native-wifi-reborn#394]
TypeError: _reactNativeWifiReborn.default.loadWifiList is not a function (it is undefined)

  try {
        const wifiArray = await WifiManager.loadWifiList();
        const newWiFiArray = removeDuplicates(wifiArray);
        if (Array.isArray(newWiFiArray) && newWiFiArray.length !== 0) {
          setWifiList(newWiFiArray);
        }
        setIsLoading(false);
      } catch (error) {
        console.log('error==========', error);
      }

 "dependencies": {
    "react": "18.2.0",
    "react-native": "0.74.3",
    "react-native-wifi-reborn": "^4.12.1",
  },

**Comment by longphung** [comment]
@Skvitthani `loadWifiList` is an Android only function because iOs doesn't support wifi scanning.

[iOS Wi-Fi API overview](https://developer.apple.com/documentation/technotes/tn3111-ios-wifi-api-overview)
> iOS does not have a general-purpose API for Wi-Fi scanning and configuration. However, it does support a wide range of special-purpose Wi-Fi APIs. This technote lists some use cases supported by those special-purpose APIs.

If you're interacting with an IOT then you would need to already know the device SSID and password, or use other methods of connection (BLE). Related [discussion](https://forums.developer.apple.com/forums/thread/113765)
