### ISSUE TITLE
Feature Request: New Architecture Support

### ISSUE THREAD

**Issue by aarongrider-sx** [JuanSeBestia/react-native-wifi-reborn#404]
Hello,
I'm wondering if someone is looking into migrating to use Fabric (i.e. the React Native New Architecture).

Opening this issue to understand what's the current status of this.

Some of the folks at [Software Mansion](https://swmansion.com/) have been contributing to add support for libraries.

**Comment by aarongrider-sx** [comment]
@WoLewicki, is this something you may be able to help with?

**Comment by WoLewicki** [comment]
Hey! We at [Software Mansion](https://swmansion.com/) have been working on [improving support](https://blog.swmansion.com/sunrising-new-architecture-in-the-new-expensify-app-729d237a02f5) for the new architecture for quite a while now. If you want us to work on migrating the library full time, contact us here: [projects@swmansion.com](mailto:projects@swmansion.com)! 

Otherwise, we can try and migrate it when we have some time, but it may take a while.
