### ISSUE TITLE
Android 10 (XiaoMi Mix2) after connecting to a IoT WIFI cannot receive multicast packets

### ISSUE THREAD

**Issue by ljbatwh** [JuanSeBestia/react-native-wifi-reborn#73]
On Android 10(Xiaomi Mix2), After connecting an IoT WIFI by connectToProtectedSSID. the multicast socket can not be received. 

But for a normal HTTP request, it will succeed.
If I connect the same IoT WIFI by manual. the multicast socket can be received.
@Rapsssito or anybody could give some idea about this?

**Comment by eliaslecomte** [comment]
What error do you get? (Also using udp).

**Comment by ljbatwh** [comment]
no errors. just not receive the multicast packets.

**Comment by Rapsssito** [comment]
@ljbatwh, in order to check if it is an issue with your IoT device or `react-native-wifi-reborn`, can you check if you can receive multicast packets in other device?

**Comment by daaanigm** [comment]
> @ljbatwh, in order to check if it is an issue with your IoT device or `react-native-wifi-reborn`, can you check if you can receive multicast packets in other device?

Hello @Rapsssito! I'm having the same problem, if wifi-reborn library is creating a wifi connection with WifiNetworkSpecifier this is not a system wifi connection, this connection is between the app and the device where you are connected. The system doesn't have internet and it is not a normal wifi connection... If we try to open a UDP connection with WifiManager (how react-native-udp do it) is creating a UDP socket but the method `addMembership` for Multicast purposes doesn't work because the Wifi service is not available.

How can we open a UDP socket connection with MULTICAST with this type of connection?

I created a related issue in react-native-udp library.
https://github.com/tradle/react-native-udp/issues/243

Thanks in advance!
