### ISSUE TITLE
Wifi list doesn't include hidden ssid wifi

### ISSUE THREAD

**Issue by CKitisak** [JuanSeBestia/react-native-wifi-reborn#98]
I have tried to get the hidden ssid network from this function `reScanAndLoadWifiList` on andriod but It seems not work.
Please give me some advice. thank you

**Comment by eliaslecomte** [comment]
Well, if it's **hidden** I don't think it will show up in the list. And probably this will also break connecting via this library.

**Comment by CKitisak** [comment]
Hi @eliaslecomte, is there any alternative ways to connect to the hidden wifi? it seems like we cannot connect to the wifi which doesn't exist on the list (from loadWifiList or reScanAndLoadWifiList).

**Comment by eliaslecomte** [comment]
You will have to make a native module yourself. You can copy bits and pieces out of https://github.com/ThanosFisherman/WifiUtils. Up to android 9 you can just create the wifi configuration. Starting android 10, you will have to use the new api. Just skip the scanning part.

In react-native-wifi-reborn we scan first so that we know if the network is in range + what the security details of the network are.

**Comment by CKitisak** [comment]
Thank you I will have a look and try.

**Comment by t-ricci-enhancers** [comment]
@eliaslecomte @CKitisak according to https://github.com/ThanosFisherman/WifiUtils/pull/93 they have merged the hidden network connection feature on the WifiUtils repository;

Would be nice to update react-native-wifi-reborn to also support specifying a hidden network name, protection and credentials in order to connect to it

**Comment by t-ricci-enhancers** [comment]
@JuanSeBestia any chance to add this change?
